services:
  app-tokoman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tokoman_app
    restart: unless-stopped
    working_dir: /var/www/tokoman
    env_file:
      - ./.env
    volumes:
      - app_vol:/var/www/tokoman
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - shared-network
  
  web-tokoman:
    image: nginx:alpine
    container_name: tokoman_web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tokoman.self.web.id
      - LETSENCRYPT_HOST=tokoman.self.web.id
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app_vol:/var/www/tokoman
    networks:
      - shared-network
    depends_on:
      - app-tokoman

networks:
  shared-network:
    external: true

volumes:
  app_vol: