services:
  app-tokoman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tokoman_app
    restart: unless-stopped
    working_dir: /var/www/tokoman
    env_file:
      - ./.env
    volumes:
      - laravel_storage:/var/www/tokoman/storage
      - laravel_cache:/var/www/tokoman/bootstrap/cache
    networks:
      - shared-network
  
  web-tokoman:
    image: nginx:alpine
    container_name: tokoman_web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tokoman.self.web.id
      - LETSENCRYPT_HOST=tokoman.self.web.id
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - laravel_storage:/var/www/tokoman/storage
      - laravel_cache:/var/www/tokoman/bootstrap/cache
    networks:
      - shared-network
    depends_on:
      - app-tokoman

networks:
  shared-network:
    external: true

volumes:
  laravel_storage:
  laravel_cache: