[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=nice -n 10 php /var/www/tokoman/artisan queue:work --queue=default --sleep=5 --tries=3 --memory=128
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/tokoman/storage/logs/worker.log
stopwaitsecs=3600
