[program:laravel-worker]
command=php /var/www/tokoman/artisan queue:work --sleep=1 --tries=3 --max-time=3600
autostart=true
autorestart=true
redirect_stderr=true
user=www-data
startsecs=2
stopwaitsecs=10
